# Generated by Django 5.1.3 on 2025-01-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_azuredeployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='azuredeployment',
            name='attack_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openaiintegration',
            name='attack_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
