# Generated by Django 5.1.3 on 2025-01-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_azuredeployment_attack_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_name', models.CharField(max_length=255)),
                ('probes_name', models.CharField(max_length=255)),
            ],
        ),
    ]
