# Generated by Django 5.1.3 on 2025-01-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_valuemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuemapping',
            name='probes_name',
            field=models.CharField(max_length=500),
        ),
    ]
