# Generated by Django 5.1.3 on 2025-01-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_probelist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProbeList',
        ),
    ]
