# Generated by Django 5.1.3 on 2025-01-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_scannerattackprobe'),
    ]

    operations = [
        migrations.AddField(
            model_name='azuredeployment',
            name='probe_lists',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openaiintegration',
            name='probe_lists',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ScannerAttackProbe',
        ),
    ]
