# Generated by Django 5.1.3 on 2025-01-28 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0010_azuredeployment_yaml_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuemapping',
            name='category_matrix',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
