# Generated by Django 4.2.18 on 2025-02-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0011_valuemapping_category_matrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitlogAzure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('goal', models.TextField()),
                ('prompt', models.TextField(max_length=4200)),
                ('output', models.TextField(max_length=4200)),
                ('trigger', models.TextField()),
                ('score', models.FloatField()),
                ('run_id', models.CharField(max_length=255)),
                ('attempt_id', models.CharField(max_length=255)),
                ('attempt_seq', models.IntegerField()),
                ('attempt_idx', models.IntegerField()),
                ('generator', models.CharField(max_length=255)),
                ('probe', models.TextField()),
                ('detector', models.CharField(max_length=255)),
                ('generations_per_prompt', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HitlogOpenAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('goal', models.TextField()),
                ('prompt', models.TextField(max_length=4200)),
                ('output', models.TextField(max_length=4200)),
                ('trigger', models.TextField()),
                ('score', models.FloatField()),
                ('run_id', models.CharField(max_length=255)),
                ('attempt_id', models.CharField(max_length=255)),
                ('attempt_seq', models.IntegerField()),
                ('attempt_idx', models.IntegerField()),
                ('generator', models.CharField(max_length=255)),
                ('probe', models.TextField()),
                ('detector', models.CharField(max_length=255)),
                ('generations_per_prompt', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
