# Generated by Django 4.2.18 on 2025-02-04 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scanner', '0012_hitlogazure_hitlogopenai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hitlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hitlog_file', models.CharField(max_length=255)),
                ('goal', models.TextField()),
                ('prompt', models.TextField()),
                ('output', models.TextField()),
                ('trigger', models.TextField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('run_id', models.CharField(max_length=255)),
                ('attempt_id', models.CharField(max_length=255)),
                ('attempt_seq', models.IntegerField()),
                ('attempt_idx', models.IntegerField()),
                ('generator', models.CharField(max_length=255)),
                ('probe', models.CharField(max_length=255)),
                ('detector', models.CharField(max_length=255)),
                ('generations_per_prompt', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='HitlogAzure',
        ),
        migrations.DeleteModel(
            name='HitlogOpenAI',
        ),
    ]
