# Generated by Django 4.2.18 on 2025-02-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0013_hitlog_delete_hitlogazure_delete_hitlogopenai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitlog',
            name='attempt_id',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='hitlog_file',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='output',
            field=models.TextField(max_length=4200),
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='prompt',
            field=models.TextField(max_length=4200),
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='run_id',
            field=models.CharField(max_length=512),
        ),
    ]
