# Generated by Django 4.2.18 on 2025-02-04 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0014_alter_hitlog_attempt_id_alter_hitlog_hitlog_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hitlog',
        ),
    ]
