# Generated by Django 4.2.18 on 2025-02-04 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scanner', '0015_delete_hitlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField(blank=True, null=True)),
                ('prompt', models.TextField()),
                ('output', models.TextField()),
                ('trigger', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('run_id', models.CharField(blank=True, max_length=512, null=True)),
                ('attempt_id', models.CharField(blank=True, max_length=512, null=True)),
                ('attempt_seq', models.IntegerField(blank=True, null=True)),
                ('attempt_idx', models.IntegerField(blank=True, null=True)),
                ('generator', models.CharField(blank=True, max_length=512, null=True)),
                ('probe', models.CharField(blank=True, max_length=512, null=True)),
                ('detector', models.CharField(blank=True, max_length=512, null=True)),
                ('generations_per_prompt', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
