# Generated by Django 4.2.18 on 2025-02-05 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0016_scanresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='yaml_name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
