# Generated by Django 4.2.18 on 2025-02-05 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0017_scanresult_yaml_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanresult',
            old_name='yaml_name',
            new_name='report_name',
        ),
    ]
