# Generated by Django 5.1.3 on 2025-01-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0009_azuredeployment_probe_lists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='azuredeployment',
            name='yaml_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='openaiintegration',
            name='yaml_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
